ax.localization:Register("fr", {
    ["subcategory.containers"] = "Conteneurs",

    ["config.container.save"] = "Conteneurs persistants",
    ["config.container.save.help"] = "Détermine si les conteneurs générés persistent après les redémarrages.",
    ["config.container.default.open_time"] = "Temps d'Ouverture par Défaut des Conteneurs",
    ["config.container.default.open_time.help"] = "Délai de secours avant qu'un conteneur s'ouvre lorsque sa définition ne le remplace pas.",
    ["config.container.default.max_weight"] = "Poids Maximal par Défaut des Conteneurs",
    ["config.container.default.max_weight.help"] = "Poids de stockage maximal de secours pour les conteneurs sans capacité de poids explicite.",
    ["config.container.password.attempt_limit"] = "Limite de Tentatives de Mot de Passe pour les Conteneurs",
    ["config.container.password.attempt_limit.help"] = "Nombre maximum de tentatives de mot de passe autorisées par conteneur verrouillé avant que d'autres tentatives soient bloquées.",
    ["config.container.password.retry_delay"] = "Délai de Nouvelle Tentative de Mot de Passe pour les Conteneurs",
    ["config.container.password.retry_delay.help"] = "Délai en secondes entre les soumissions de mot de passe.",

    ["container.your_inventory"] = "Votre Inventaire",
    ["container.item_column"] = "Objet",
    ["container.take_button"] = "<< Prendre",
    ["container.store_button"] = "Stocker >>",
    ["container.title"] = "Conteneur de Stockage",
    ["container.contents_title"] = "Conteneur",
    ["container.transfer_actions"] = "TRANSFERT",
    ["container.drag_hint"] = "Faites glisser les objets entre les volets ou utilisez les boutons de transfert.",
    ["container.empty_inventory"] = "Rien n'est encore stocké ici.",
    ["container.capacity"] = "Capacité : %s%s / %s%s",
    ["container.open_time"] = "Temps d'Ouverture : %.1fs",
    ["container.money"] = "Argent : %d",
    ["container.move_items"] = "Déplacez les objets entre votre inventaire et ce conteneur.",
    ["container.opening"] = "Ouverture de %s...",
    ["container.locked"] = "🔒 Verrouillé",
    ["container.unlocked"] = "🔓 Déverrouillé",
    ["container.password.title"] = "Mot de Passe du conteneur",
    ["container.password.prompt"] = "Entrez le mot de passe pour ce conteneur :",
    ["container.password.incorrect"] = "Ce mot de passe est incorrect.",
    ["container.password.limit"] = "Vous avez atteint la limite de tentatives de mot de passe.",
    ["container.not_ready"] = "Ce conteneur n'est pas encore prêt.",
    ["container.search_your_inventory"] = "Rechercher dans Votre Inventaire",
    ["container.search_container_inventory"] = "Rechercher dans le conteneur",

    ["container.property.set_password"] = "Définir le Mot de Passe",
    ["container.property.set_password.prompt"] = "Entrez un nouveau mot de passe. Laissez vide pour le supprimer :",
    ["container.property.set_name"] = "Définir le Nom",
    ["container.property.set_name.prompt"] = "Entrez un nouveau nom d'affichage. Laissez vide pour le réinitialiser :",
    ["container.password.updated"] = "Mot de passe du conteneur mis à jour.",
    ["container.password.cleared"] = "Mot de passe du conteneur supprimé.",
    ["container.name.updated"] = "Nom du conteneur mis à jour.",
    ["container.name.reset"] = "Nom du conteneur réinitialisé.",

})
